workflows:
  ios-simulator:
    name: iOS Simulator
    instance_type: mac_mini_m2
    max_build_duration: 30
    working_directory: apps/mobile
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Dépendances
        script: flutter pub get
      - name: Build simulateur
        script: flutter build ios --simulator --debug
      - name: Zip de l'app
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.app.zip Runner.app
    artifacts:
      - apps/mobile/build/ios/iphonesimulator/Runner.app.zip