services:
  - type: web
    name: elite-placo-api
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: apps/api/Dockerfile
    dockerContext: apps/api
    healthCheckPath: /actuator/health
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: elite-placo-db-frankfurt
          property: host
      - key: DB_PORT
        fromDatabase:
          name: elite-placo-db-frankfurt
          property: port
      - key: DB_NAME
        fromDatabase:
          name: elite-placo-db-frankfurt
          property: database
      - key: DB_USER
        fromDatabase:
          name: elite-placo-db-frankfurt
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: elite-placo-db-frankfurt
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: CORS_ORIGINS
        value: https://eliteplacodeco.cm,https://elite-placo-site.onrender.com,https://elite-placo-app.onrender.com,https://elite-placo-site-9q65.onrender.com,https://elite-placo-app-9q65.onrender.com
      - key: APP_DEMO_ENABLED
        value: "false"

  - type: web
    name: elite-placo-site
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: apps/web/Dockerfile
    dockerContext: apps/web
    healthCheckPath: /

  - type: web
    name: elite-placo-app
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: apps/mobile/Dockerfile
    dockerContext: apps/mobile
    healthCheckPath: /

databases:
  - name: elite-placo-db-frankfurt
    region: frankfurt
    databaseName: eliteplaco
    user: eliteplaco
    plan: free
